# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email: "fakeartist@fake.com", password: "testing1")
Recipe.create(name: "Root Beer Pulled Pork Sandwiches", directions: "1. Place the pork in a slow cooker and pour the can of root beer over the meat. Cover and cook on low for 6 hours or until pork shreds easily with a fork.
2. After pork has cooked, drain and discard the root beer. Shred the pork and place it back in the slow cooker. Pour the barbecue sauce over the pork and stir to combine. Serve immediately or keep warm in slow cooker until ready to serve. Serve on hamburger buns.
", difficulty: 2, servings: 8, image_url: "http://4.bp.blogspot.com/-plkksF0qN0A/Td6V5wXmW3I/AAAAAAAAG6s/ctar83hZ7Zk/s640/pulled-pork-thumb.JPG")
Ingredient.create(name: "1 (2 pound) pork shoulder or butt (tenderloin can be used for a leaner option)")
Ingredient.create(name: "1 (12 ounce) can of root beer")
Ingredient.create(name: "1 (18 ounce) bottle of barbacue sauce")
Ingredient.create(name: "8 hamburger buns")
RecipeIngredient.create(ingredient_id: 1, recipe_id: 1)
RecipeIngredient.create(ingredient_id: 2, recipe_id: 1)
RecipeIngredient.create(ingredient_id: 3, recipe_id: 1)
RecipeIngredient.create(ingredient_id: 4, recipe_id: 1)
Favorite.create(user_id: 1, recipe_id: 1)
Recipe.create(name: "Nutella Crescent Rolls", directions: "1. Preheat oven to 350 degrees F, and line a baking sheet with parchment paper. Unroll the crescent roll dough. Spread a thin layer of nutella on each piece of dough (stopping about an inch or two before the end of the skinnier side). Roll the crescent rolls up. After they’re rolled up, make sure you roll them back and forth a couple of times to seal the edges of the dough. 2. Bake in the oven for 12-15 minutes or until the tops are golden brown. Let cool for about 5-10 minutes and then dust with some powdered sugar. The rolls can be served immediately or last a couple of days if tightly wrapped.
", difficulty: 1, servings: 4, image_url: "http://www.lifetasteslikefood.com/wp-content/uploads/2012/02/IMG_9417-1024x701.jpg")
Ingredient.create(name: "1 package of Pilsbury Crescent Rolls (8 count)")
Ingredient.create(name: "Nutella")
Ingredient.create(name: "Powdered sugar")
RecipeIngredient.create(ingredient_id: 5, recipe_id: 2)
RecipeIngredient.create(ingredient_id: 6, recipe_id: 2)
RecipeIngredient.create(ingredient_id: 7, recipe_id: 2)
Favorite.create(user_id: 1, recipe_id: 2)
Recipe.create(name: "Four-Ingredient Red Curry Chicken", directions: "1. Heat oil in a large skillet on high heat. Add chicken cubes; cook until browned, about 2 minutes per side. Reduce heat to medium-high and add coconut cream and curry sauce. Cook until chicken is no longer pink in the center and the juices run clear, about 5 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C). 2. Fill a large pot with lightly salted water and bring to a rolling boil; stir in vermicelli pasta and return to a boil. Cook pasta uncovered, stirring occasionally, until the pasta is tender yet firm to the bite, 4 to 5 minutes. Drain. 3. Reduce skillet heat to simmer. Add the noodles and let simmer until flavors are absorbed, about 5 minutes. Divide chicken and noodles among individual serving bowls.", difficulty: 2, servings: 6, image_url: "https://images.media-allrecipes.com/userphotos/560x315/3949345.jpg")
Ingredient.create(name: "2 tablespoons coconut oil")
Ingredient.create(name: "1 (16 ounce) package skinless, boneless chicken breast halves, cut into small cubes")
Ingredient.create(name: "1 (14 ounce) can cream of coconut (such as Trader Joe's® Extra Thick and Rich)")
Ingredient.create(name: "1 (11 ounce) bottle red Thai curry sauce (such as Trader Joe's®)")
Ingredient.create(name: "1/2 (16 ounce) package dried rice stick vermicelli noodles")
RecipeIngredient.create(ingredient_id: 8, recipe_id: 3)
RecipeIngredient.create(ingredient_id: 9, recipe_id: 3)
RecipeIngredient.create(ingredient_id: 10, recipe_id: 3)
RecipeIngredient.create(ingredient_id: 11, recipe_id: 3)
RecipeIngredient.create(ingredient_id: 12, recipe_id: 3)
Favorite.create(user_id: 1, recipe_id: 3)
Recipe.create(name: "Grilled Shrimp Tacos", directions: "1. Heat grill to medium-high. In a small bowl, whisk together the sour cream, mayonnaise, milk, and cumin. Set aside. 2. Skewer the shrimp. (If using wood skewers, soak them in water for 10 minutes beforehand.) In a small bowl, combine the butter and garlic. Brush the shrimp with the garlic butter. 3. Place the shrimp on grill with the limes. Cook for about 4 minutes on each side or until the shrimp are opaque and the limes are browned. 4. Remove from grill. Lightly salt the shrimp. 5. Grill the tortillas for 30 seconds on each side, then place inside a paper bag to keep warm. 6. Pull the shrimp off the skewers; divide evenly among the tortillas. Top with the cabbage, sour cream sauce, tomatillo salsa, and a squeeze of grilled lime.", difficulty: 4, servings: 4, image_url: "https://www.onceuponachef.com/images/2012/05/shrimp-tacos-1.jpg")
Ingredient.create(name: "1/2 cup sour cream")
Ingredient.create(name: "3 tablespoons mayonnaise")
Ingredient.create(name: "3 tablespoons milk")
Ingredient.create(name: "1/2 teaspoon ground cumin")
Ingredient.create(name: "1 1/2 pounds large shrimp, peeled")
Ingredient.create(name: "3 tablespoons butter, melted")
Ingredient.create(name: "2 large garlic cloves, minced")
Ingredient.create(name: "4 limes, cut into quarters")
Ingredient.create(name: "kosher salt")
Ingredient.create(name: "8 6-inch corn tortillas")
Ingredient.create(name: "2 to 3 cups finely shredded green cabbage")
Ingredient.create(name: "jarred green tomatillo salsa")
RecipeIngredient.create(ingredient_id: 13, recipe_id: 4)
RecipeIngredient.create(ingredient_id: 14, recipe_id: 4)
RecipeIngredient.create(ingredient_id: 15, recipe_id: 4)
RecipeIngredient.create(ingredient_id: 16, recipe_id: 4)
RecipeIngredient.create(ingredient_id: 17, recipe_id: 4)
RecipeIngredient.create(ingredient_id: 18, recipe_id: 4)
RecipeIngredient.create(ingredient_id: 19, recipe_id: 4)
RecipeIngredient.create(ingredient_id: 20, recipe_id: 4)
RecipeIngredient.create(ingredient_id: 21, recipe_id: 4)
RecipeIngredient.create(ingredient_id: 22, recipe_id: 4)
RecipeIngredient.create(ingredient_id: 23, recipe_id: 4)
Favorite.create(user_id: 1, recipe_id: 4)
Recipe.create(name: "Slow Cooker Beef Stew", directions: "1. Toss the beef with the paprika, 1 1/2 teaspoons salt and 1/2 teaspoon pepper. Coat in flour and shake off any excess. Heat 2 tablespoons of the oil in a large nonstick skillet over medium-high heat. Add the beef and cook undisturbed until it begins to brown, about 3 minutes. Continue to cook, turning the beef as needed, until mostly browned, about 3 minutes more. Remove the skillet from the heat and transfer the beef to the insert of a 6-quart slow cooker; add the potatoes, mushrooms, carrots and onions and stir to combine. 2. Heat the remaining 1 tablespoon of oil in the skillet over medium heat. Add the tomato paste and stir until the oil begins to turn brick-red, about 1 minute. Add the flour and wine and whisk until thick (it's OK if there are some lumps). Add the beef broth, thyme, caraway if using, 1/2 teaspoon salt and a few grinds of pepper and bring to a simmer, whisking; continue simmering and whisking until the gravy is smooth and thick, about 4 minutes. 3. Pour the gravy into the slow cooker, cover and cook on low for 8 hours. The meat and vegetables should be tender. 4. Season with salt and pepper and stir in the parsley. Serve the stew in bowls with dollops of sour cream and a sprinkle of paprika.", difficulty: 1, servings: 8, image_url: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2013/11/27/0/FN_Slow-Cooker-Beef-Stew_s4x3.jpg.rend.hgtvcom.616.462.suffix/1386172173354.jpeg")
Ingredient.create(name: "2 pounds beef chuck, cut into 1 1/2-inch pieces")
Ingredient.create(name: "1 teaspoon sweet paprika, plus more for garnish")
Ingredient.create(name: "Kosher salt and freshly ground black pepper")
Ingredient.create(name: "1/3 cup all-purpose flour, plus more for coating")
Ingredient.create(name: "3 tablespoons olive oil")
Ingredient.create(name: "1 pound small white potatoes, halved")
Ingredient.create(name: "1/2 pound cremini mushrooms, halved")
Ingredient.create(name: "3 medium carrots, cut into 1-inch chunks")
Ingredient.create(name: "1 medium onion, chopped")
Ingredient.create(name: "2 tablespoons tomato paste")
Ingredient.create(name: "1 cup red wine")
Ingredient.create(name: "2 cups low-sodium beef broth")
Ingredient.create(name: "3 sprigs fresh thyme")
Ingredient.create(name: "1 teaspoon caraway seeds, optional")
Ingredient.create(name: "1/2 cup loosely packed parsley leaves, chopped")
Ingredient.create(name: "Sour cream, for serving")
RecipeIngredient.create(ingredient_id: 24, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 25, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 26, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 27, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 28, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 29, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 30, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 31, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 32, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 33, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 34, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 35, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 36, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 37, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 38, recipe_id: 5)
RecipeIngredient.create(ingredient_id: 39, recipe_id: 5)
Favorite.create(user_id: 1, recipe_id: 5)
Recipe.create(name: "Buffalo Chicken Wings", directions: "1. Preheat the broiler. 2. Cut the chicken wings in thirds, cutting between the bones. 3. Discard the wing tips. 4. Melt the butter and add the cayenne, hot sauce, and salt. 5. Put the wings on a sheet pan and brush them with the melted butter. 6. Broil them about 3 inches below the heat for 8 minutes. Turn the wings, brush them again with the butter, and broil for 4 more minutes or until cooked. 7. For the sauce, place the blue cheese, mayonnaise, sour cream, milk, Worcestershire, salt, and pepper in the bowl of a food processor fitted with a steel blade. Process until almost smooth. 8. Serve the chicken wings hot or at room temperature with the blue cheese dip and celery sticks.", difficulty: 1, servings: 4, image_url: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2013/9/28/0/FNK_Buffalo-Style-Chicken-Wings_s4x3.jpg.rend.hgtvcom.616.462.suffix/1383780068425.jpeg")
Ingredient.create(name: "16 chicken wings (about 3 pounds)")
Ingredient.create(name: "1/4 pound (1 stick) unsalted butter")
Ingredient.create(name: "1 teaspoon cayenne pepper")
Ingredient.create(name: "4 teaspoons Frank's Hot Sauce, or 1 teaspoon Tabasco")
Ingredient.create(name: "1 teaspoon kosher salt")
Ingredient.create(name: "1 1/2 cups crumbled Gorgonzola or other blue cheese")
Ingredient.create(name: "1 cup good mayonnaise")
Ingredient.create(name: "3/4 cup sour cream")
Ingredient.create(name: "2 tablespoons milk")
Ingredient.create(name: "3/4 teaspoon Worcestershire sauce")
Ingredient.create(name: "1 1/2 teaspoons kosher salt")
Ingredient.create(name: "3/4 teaspoon freshly ground black pepper")
Ingredient.create(name: "Celery sticks, for serving")
RecipeIngredient.create(ingredient_id: 40, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 41, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 42, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 43, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 44, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 45, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 46, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 47, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 48, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 49, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 50, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 51, recipe_id: 6)
RecipeIngredient.create(ingredient_id: 52, recipe_id: 6)
Favorite.create(user_id: 1, recipe_id: 6)
Recipe.create(name: "Sweet and Sour Chicken", directions: "1. Combine egg whites and 1 tablespoon cornstarch in a large bowl, stirring with a whisk. Add chicken to bowl; toss to coat. 2. Combine remaining 1 teaspoon cornstarch, ketchup, and next 4 ingredients (through soy sauce) in a bowl, stirring with a whisk. 3. Heat a large nonstick skillet over medium-high heat. Add 1 tablespoon oil to pan; swirl to coat. Add bell pepper to pan; cook 2 minutes, stirring frequently. Add pineapple, ginger, and onions to pan; cook 2 minutes, stirring occasionally. Transfer bell pepper mixture to a plate. 4. Add remaining 1 tablespoon oil to pan. Add chicken mixture, allowing any excess egg white mixture to drip back into bowl. Stir-fry 6 minutes or until chicken is browned and done. Add ketchup mixture and bell pepper mixture to pan. Bring to a simmer; simmer 1 minute or until slightly thickened. Sprinkle with salt; serve immediately.", difficulty: 3, servings: 4, image_url: "https://imagesvc.timeincapp.com/v3/mm/image?url=http%3A%2F%2Fcdn-image.myrecipes.com%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fmedium_2x%2Fpublic%2Fsweet-sour-chicken-ck.jpg%3Fitok%3DasmlHhHr&w=1600&q=70")
Ingredient.create(name: "2 large egg whites")
Ingredient.create(name: "4 teaspoons cornstarch, divided")
Ingredient.create(name: "1 pound skinless, boneless chicken breasts, cut into 1-inch pieces")
Ingredient.create(name: "6 tablespoons unsalted ketchup")
Ingredient.create(name: "1/4 cup water")
Ingredient.create(name: "3 tablespoons cider vinegar")
Ingredient.create(name: "2 tablespoons brown sugar")
Ingredient.create(name: "1 1/2 tablespoons lower-sodium soy sauce")
Ingredient.create(name: "2 tablespoons canola oil, divided")
Ingredient.create(name: "1 red bell pepper, cut into 1-inch pieces")
Ingredient.create(name: "1 1/2 cups fresh pineapple chunks")
Ingredient.create(name: "2 teaspoons grated fresh ginger")
Ingredient.create(name: "3 green onions, cut into 1-inch pieces")
Ingredient.create(name: "3/8 teaspoon kosher salt")
RecipeIngredient.create(ingredient_id: 53, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 54, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 55, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 56, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 57, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 58, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 59, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 60, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 61, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 62, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 63, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 64, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 65, recipe_id: 7)
RecipeIngredient.create(ingredient_id: 66, recipe_id: 7)
Favorite.create(user_id: 1, recipe_id: 7)
Recipe.create(name: "Tortellini in Brodo", directions: "1. Heat the olive oil in a large pot over medium heat. 2. Add the leeks, carrots, celery and garlic and cook, stirring occasionally, until the leeks wilt, about 5 minutes. 3. Add 2 cups water, the chicken broth, parmesan rind, lemon zest and pork bone. 4. Bring to a simmer and cook until the vegetables are almost tender, about 15 minutes. 5. Remove the parmesan rind, lemon zest and pork bone from the pot with a slotted spoon. 6. Bring the broth to a boil over medium heat. Add the tortellini, escarole and diced pork; season with pepper. Cook until the tortellini and escarole are tender, 4 to 5 minutes.", difficulty: 2, servings: 4, image_url: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2017/1/18/0/FNM030117_Tortellini-in-Brodo_s4x3.jpg.rend.hgtvcom.616.462.suffix/1484758875650.jpeg")
Ingredient.create(name: "2 tablespoons extra-virgin olive oil")
Ingredient.create(name: "2 leeks (white and light green parts only), halved lengthwise, thinly sliced and rinsed")
Ingredient.create(name: "2 carrots, halved lengthwise and thinly sliced")
Ingredient.create(name: "2 small celery stalks, thinly sliced")
Ingredient.create(name: "4 cloves garlic, smashed")
Ingredient.create(name: "4 cups low-sodium chicken broth")
Ingredient.create(name: "1 small piece parmesan rind")
Ingredient.create(name: "2 wide strips lemon zest (removed with a vegetable peeler)")
Ingredient.create(name: "1 12-ounce bone-in smoked pork chop, diced (bone reserved)")
Ingredient.create(name: "1 9-ounce package refrigerated cheese or meat tortellini")
Ingredient.create(name: "1 small head escarole, chopped")
Ingredient.create(name: "Freshly ground pepper")
RecipeIngredient.create(ingredient_id: 65, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 66, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 67, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 68, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 69, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 70, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 71, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 72, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 73, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 74, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 75, recipe_id: 8)
RecipeIngredient.create(ingredient_id: 76, recipe_id: 8)
Favorite.create(user_id: 1, recipe_id: 8)
Recipe.create(name: "Pork Chops Pizzaiola", directions: "1. Season chops with salt and pepper. 2. Heat the extra-virgin olive oil in large skillet over medium-high heat. 3. Add the crushed garlic and stir it around to flavor the oil. 4. Add in the chops and caramelize on both sides, 2 to 3 minutes per side. 5. Remove the chops to a plate and reserve. 6. Stir in the fennel seed, onions, red pepper flakes, and oregano. 7. Reduce the heat and cook for 7 to 8 minutes. 8. Add the tomato paste, and cook for 1 minute, then add the wine, and cook for another minute. 9. Stir in the stock and combine well. 10. Slide the chops back into the pan, cover and simmer to finish cooking the chops, about 5 to 6 minutes. 11. Arrange the chops and sauce on a serving platter and serve.", difficulty: 5, servings: 4, image_url: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2014/3/25/1/TM2107_Pork-Chops-Pizzaiola_s4x3.jpg.rend.hgtvcom.616.462.suffix/1396271489196.jpeg")
Ingredient.create(name: "4 (1 1/2-inch thick) bone-in pork chops")
Ingredient.create(name: "Kosher salt and freshly ground black pepper")
Ingredient.create(name: "2 tablespoons extra-virgin olive oil")
Ingredient.create(name: "1 large clove garlic, crushed")
Ingredient.create(name: "1 teaspoon fennel seed")
Ingredient.create(name: "1 medium onion, chopped")
Ingredient.create(name: "1 teaspoon crushed red pepper flakes")
Ingredient.create(name: "2 sprigs fresh oregano, leaves chopped, or 1 teaspoon dried oregano")
Ingredient.create(name: "1/4 cup tomato paste")
Ingredient.create(name: "1 cup red wine")
Ingredient.create(name: "2 cups chicken stock")
RecipeIngredient.create(ingredient_id: 75, recipe_id: 9)
RecipeIngredient.create(ingredient_id: 76, recipe_id: 9)
RecipeIngredient.create(ingredient_id: 77, recipe_id: 9)
RecipeIngredient.create(ingredient_id: 78, recipe_id: 9)
RecipeIngredient.create(ingredient_id: 79, recipe_id: 9)
RecipeIngredient.create(ingredient_id: 80, recipe_id: 9)
RecipeIngredient.create(ingredient_id: 81, recipe_id: 9)
RecipeIngredient.create(ingredient_id: 82, recipe_id: 9)
RecipeIngredient.create(ingredient_id: 83, recipe_id: 9)
RecipeIngredient.create(ingredient_id: 84, recipe_id: 9)
RecipeIngredient.create(ingredient_id: 85, recipe_id: 9)
Favorite.create(user_id: 1, recipe_id: 9)









